# Installing Ruby 2.7.3 using the official Ruby docker image.
FROM ruby:2.7.0

# Setting up Application Directory 
ENV INSTALL_PATH /opt/app

COPY ./ /opt/app/rails-rennie
COPY ./Gemfile-docker ./opt/app/rails-rennie/Gemfile

RUN mkdir -p $INSTALL_PATH

# Setting up rails-rennie docker container files 

COPY ./.env.docker /opt/app/rails-rennie/.env
COPY ./config/geocoder.docker.rb /opt/app/rails-rennie/config/initializers/geocoder.rb
COPY ./config/database.docker.yml /opt/app/rails-rennie/config/database.yml

# Installing package depedancies for various different package dependacies required to run rails-rennie inside the docker container

RUN apt-get install curl
RUN apt-get update && \
    apt-get -y install sudo && \
    apt-get -y install git && \
    apt-get -y install shared-mime-info && \
    apt-get -y install postgresql-client && \
    apt-get -y install vim && \
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && \
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash && \
    apt-get -y install nodejs && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ rc main" | sudo tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get -y install yarn

ENV NVM_DIR=/root/.nvm
ENV NODE_VERSION=v9.4.0

RUN . $HOME/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION && nvm use default

RUN echo 'alias docker-start-r2="/opt/app/rails-rennie/initialize-r2-docker.sh"' >> ~/.bashrc

#Sets default working directory for the application

WORKDIR /opt/app/rails-rennie

# Install rails using bundler version 2.1.2 

RUN gem install bundler -v 2.1.2

# Install rails-rennie gem dependacies 
RUN MAKE="make --jobs 4" bundle install --path=vendor/bundle
#RUN bundle install --path=vendor/bundle

# Run a shell
CMD ["/bin/sh"]

# Exposing the docker container ports in order for us to be able to visit it using localhost. 
EXPOSE 5432
EXPOSE 3000

# ENTRYPOINT ["./entrypoints/docker-entrypoint.sh"]
